######################################
# docker file to build snort2.9 container images
# based on centos7
######################################

#SET THE BASE IMAGE
#FROM insaneworks/centos
FROM mysql:version1.0

#FILE AUTHOR
MAINTAINER czpfreedom

######### BEGIN INSTALLATION ##########
RUN yum -y install  libpcap* zlib*  libtermcap*  tcpdump bison flex git

#INSTALL PCRE
WORKDIR /home
RUN wget https://ftp.pcre.org/pub/pcre/pcre-8.00.tar.gz 
RUN tar -zxvf pcre-8.00.tar.gz
WORKDIR ./pcre-8.00
RUN ./configure
RUN make && make install

#INSTALL DAQ
WORKDIR /home
RUN wget https://www.snort.org/downloads/snort/daq-2.0.6.tar.gz
RUN tar -zxvf daq-2.0.6.tar.gz
WORKDIR ./daq-2.0.6
RUN ./configure
RUN make && make install 

#INSTALL LIBDNET
WORKDIR /home
RUN git clone https://github.com/dugsong/libdnet.git
WORKDIR ./libdnet
RUN ./configure
RUN make && make install

#INSTALL SNORT
WORKDIR /home
RUN wget https://www.snort.org/downloads/snort/snort-2.9.11.1.tar.gz
RUN tar -zxvf snort-2.9.11.1.tar.gz
WORKDIR ./snort-2.9.11.1
RUN cp /home/libdnet/include/dnet/sctp.h  /usr/local/include/dnet
RUN ./configure --prefix=/usr/local
RUN make && make install

#INSTALL BARNYARD2
WORKDIR /home
RUN wget https://github.com/firnsy/barnyard2/archive/v2-1.13.tar.gz -O barnyard2-2-1.13.tar.gz
RUN tar -zxvf barnyard2-2-1.13.tar.gz
WORKDIR ./barnyard2-2-1.13
RUN yum -y install libmysqlclient-dev autoconf libtool
RUN autoreconf -fvi -I ./m4
RUN ./configure --with-mysql --with-mysql-libraries=/usr/local/mysql/lib/mysql --with-mysql-includes=/usr/local/mysql/include/mysql
RUN make && make install && mkdir /home/snort-2.9.11.1/etc/community-rules/ && cp /home/barnyard2-2-1.13/schemas/create_mysql /usr/src
## RUN r /var/log/snort && mkdir /var/log/snort
COPY snort.conf barnyard2.conf snort1.sql snort2.sql README /home/snort-2.9.11.1/etc/ 
COPY community-rules /home/snort-2.9.11.1/etc/community-rules/

