######################################
# docker file to build snort2.9 container images
# based on centos7
######################################

#SET THE BASE IMAGE
#FROM insaneworks/centos
FROM centos:centos7

#FILE AUTHOR
MAINTAINER czpfreedom

######### BEGIN INSTALLATION ##########
RUN yum -y install epel-release wget vim gcc gcc-c++ libpcap* zlib* tar ncurses* libtermcap* make tcpdump bison flex git

#INSTALL PCRE
WORKDIR /home
RUN wget https://ftp.pcre.org/pub/pcre/pcre-8.00.tar.gz 
RUN tar -zxvf pcre-8.00.tar.gz
WORKDIR ./pcre-8.00
RUN ./configure
RUN make && make install

#INSTALL DAQ
WORKDIR /home
RUN wget https://www.snort.org/downloads/snort/daq-2.0.6.tar.gz
RUN tar -zxvf daq-2.0.6.tar.gz
WORKDIR ./daq-2.0.6
RUN ./configure
RUN make && make install 

#INSTALL LIBDNET
WORKDIR /home
RUN git clone https://github.com/dugsong/libdnet.git
WORKDIR ./libdnet
RUN ./configure
RUN make && make install

#INSTALL SNORT
WORKDIR /home
RUN wget https://www.snort.org/downloads/snort/snort-2.9.11.1.tar.gz
RUN tar -zxvf snort-2.9.11.1.tar.gz
WORKDIR ./snort-2.9.11.1
RUN cp /home/libdnet/include/dnet/sctp.h  /usr/local/include/dnet
RUN ./configure --prefix=/usr/local
RUN make && make install
